#Analyze_Plot+sum-stat.R
#Chen Keyu- 2022.11.14

library(pacman)

p_load(dplyr,data.table,ggplot2,lubridate,vtable,gtools)

setwd("~/Social Network and Vaccination")

df <- readRDS("Data/Final Data/state-sample-123999.rds")

df$median5 <- as.numeric(quantcut(df$friendvax_week5, q = 2, na.rm = TRUE))
df$median6 <- as.numeric(quantcut(df$friendvax_week6, q = 2, na.rm = TRUE))
df$median7 <- as.numeric(quantcut(df$friendvax_week7, q = 2, na.rm = TRUE))
df$median8 <- as.numeric(quantcut(df$friendvax_week8, q = 2, na.rm = TRUE))
df$median9 <- as.numeric(quantcut(df$friendvax_week9, q = 2, na.rm = TRUE))
df$median10 <- as.numeric(quantcut(df$friendvax_week10, q = 2, na.rm = TRUE))
df$median11 <- as.numeric(quantcut(df$friendvax_week11, q = 2, na.rm = TRUE))
df$median12 <- as.numeric(quantcut(df$friendvax_week12, q = 2, na.rm = TRUE))
df$median13 <- as.numeric(quantcut(df$friendvax_week13, q = 2, na.rm = TRUE))
df$median14 <- as.numeric(quantcut(df$friendvax_week14, q = 2, na.rm = TRUE))
df$median15 <- as.numeric(quantcut(df$friendvax_week15, q = 2, na.rm = TRUE))
df$median16 <- as.numeric(quantcut(df$friendvax_week16, q = 2, na.rm = TRUE))
df$median17 <- as.numeric(quantcut(df$friendvax_week17, q = 2, na.rm = TRUE))
df$median18 <- as.numeric(quantcut(df$friendvax_week18, q = 2, na.rm = TRUE))
df$median19 <- as.numeric(quantcut(df$friendvax_week19, q = 2, na.rm = TRUE))
df$median20 <- as.numeric(quantcut(df$friendvax_week20, q = 2, na.rm = TRUE))
df$median21 <- as.numeric(quantcut(df$friendvax_week21, q = 2, na.rm = TRUE))
df$median22 <- as.numeric(quantcut(df$friendvax_week22, q = 2, na.rm = TRUE))
df$median23 <- as.numeric(quantcut(df$friendvax_week23, q = 2, na.rm = TRUE))
df$median24 <- as.numeric(quantcut(df$friendvax_week24, q = 2, na.rm = TRUE))
df$median25 <- as.numeric(quantcut(df$friendvax_week25, q = 2, na.rm = TRUE))
df$median26 <- as.numeric(quantcut(df$friendvax_week26, q = 2, na.rm = TRUE))
df$median27 <- as.numeric(quantcut(df$friendvax_week27, q = 2, na.rm = TRUE))
df$median28 <- as.numeric(quantcut(df$friendvax_week28, q = 2, na.rm = TRUE))
df$median29 <- as.numeric(quantcut(df$friendvax_week29, q = 2, na.rm = TRUE))
df$median30 <- as.numeric(quantcut(df$friendvax_week30, q = 2, na.rm = TRUE))
df$median31 <- as.numeric(quantcut(df$friendvax_week31, q = 2, na.rm = TRUE))
df$median32 <- as.numeric(quantcut(df$friendvax_week32, q = 2, na.rm = TRUE))
df$median33 <- as.numeric(quantcut(df$friendvax_week33, q = 2, na.rm = TRUE))

df_vax <- df[c(20:48,130:156)]


aggregate(df_vax$vax_week5,list(df_vax$median5),mean, na.rm = TRUE)
aggregate(df_vax$vax_week6,list(df_vax$median6),mean, na.rm = TRUE)
aggregate(df_vax$vax_week7,list(df_vax$median7),mean, na.rm = TRUE)
aggregate(df_vax$vax_week8,list(df_vax$median8),mean, na.rm = TRUE)
aggregate(df_vax$vax_week9,list(df_vax$median9),mean, na.rm = TRUE)
aggregate(df_vax$vax_week10,list(df_vax$median10),mean, na.rm = TRUE)
aggregate(df_vax$vax_week11,list(df_vax$median11),mean, na.rm = TRUE)
aggregate(df_vax$vax_week12,list(df_vax$median12),mean, na.rm = TRUE)
aggregate(df_vax$vax_week13,list(df_vax$median13),mean, na.rm = TRUE)
aggregate(df_vax$vax_week14,list(df_vax$median14),mean, na.rm = TRUE)
aggregate(df_vax$vax_week15,list(df_vax$median15),mean, na.rm = TRUE)
aggregate(df_vax$vax_week16,list(df_vax$median16),mean, na.rm = TRUE)
aggregate(df_vax$vax_week17,list(df_vax$median17),mean, na.rm = TRUE)
aggregate(df_vax$vax_week18,list(df_vax$median18),mean, na.rm = TRUE)
aggregate(df_vax$vax_week19,list(df_vax$median19),mean, na.rm = TRUE)
aggregate(df_vax$vax_week20,list(df_vax$median20),mean, na.rm = TRUE)
aggregate(df_vax$vax_week21,list(df_vax$median21),mean, na.rm = TRUE)
aggregate(df_vax$vax_week22,list(df_vax$median22),mean, na.rm = TRUE)
aggregate(df_vax$vax_week23,list(df_vax$median23),mean, na.rm = TRUE)
aggregate(df_vax$vax_week24,list(df_vax$median24),mean, na.rm = TRUE)
aggregate(df_vax$vax_week25,list(df_vax$median25),mean, na.rm = TRUE)
aggregate(df_vax$vax_week26,list(df_vax$median26),mean, na.rm = TRUE)
aggregate(df_vax$vax_week27,list(df_vax$median27),mean, na.rm = TRUE)
aggregate(df_vax$vax_week28,list(df_vax$median28),mean, na.rm = TRUE)
aggregate(df_vax$vax_week29,list(df_vax$median29),mean, na.rm = TRUE)
aggregate(df_vax$vax_week30,list(df_vax$median30),mean, na.rm = TRUE)
aggregate(df_vax$vax_week31,list(df_vax$median31),mean, na.rm = TRUE)
aggregate(df_vax$vax_week32,list(df_vax$median32),mean, na.rm = TRUE)
aggregate(df_vax$vax_week33,list(df_vax$median33),mean, na.rm = TRUE)
